sonar.projectKey=itsDaiton_nebula-chat
sonar.organization=itsdaiton
sonar.projectName=nebula-chat

sonar.sources=frontend/src,backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/generated/**

sonar.sourceEncoding=UTF-8

# Turn off coverage for now since it's not set up yet
sonar.coverage.exclusions=**/*
