name: Knip Code Analysis

on:
  workflow_dispatch:

jobs:
  knip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.14.1
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Run knip
        run: pnpm knip
